"""Sales Dashboard — generated by phase3_dashboard.py"""
from pathlib import Path

import pandas as pd
import plotly.express as px
from shiny import App, reactive, render, ui
from shinywidgets import output_widget, render_widget

# Load data relative to this file's location
DATA_PATH = Path(__file__).parent / "features.csv"

df_all = pd.read_csv(DATA_PATH, parse_dates=["date"])

ALL_REGIONS = sorted(df_all["region"].unique().tolist())
ALL_PRODUCTS = sorted(df_all["product"].unique().tolist())

app_ui = ui.page_fluid(
    ui.h2("Sales Dashboard"),
    ui.layout_sidebar(
        ui.sidebar(
            ui.input_checkbox_group(
                "region",
                "Region",
                choices=ALL_REGIONS,
                selected=ALL_REGIONS,
            ),
            ui.input_checkbox_group(
                "product",
                "Product",
                choices=ALL_PRODUCTS,
                selected=ALL_PRODUCTS,
            ),
        ),
        ui.row(
            ui.column(4, ui.value_box("Total Revenue", ui.output_text("kpi_revenue"), showcase=None)),
            ui.column(4, ui.value_box("Total Profit", ui.output_text("kpi_profit"), showcase=None)),
            ui.column(4, ui.value_box("Avg Units Sold", ui.output_text("kpi_units"), showcase=None)),
        ),
        output_widget("revenue_by_region"),
        output_widget("revenue_trend"),
    ),
)


def server(input, output, session):
    @reactive.calc
    def filtered():
        regions = list(input.region())
        products = list(input.product())
        mask = df_all["region"].isin(regions) & df_all["product"].isin(products)
        return df_all[mask]

    @render.text
    def kpi_revenue():
        return f"${filtered()['revenue'].sum():,.0f}"

    @render.text
    def kpi_profit():
        return f"${filtered()['profit'].sum():,.0f}"

    @render.text
    def kpi_units():
        df = filtered()
        avg = df["units_sold"].mean() if not df.empty else 0
        return f"{avg:.1f}"

    @render_widget
    def revenue_by_region():
        df = filtered().groupby("region", as_index=False)["revenue"].sum()
        return px.bar(df, x="region", y="revenue", title="Total Revenue by Region",
                      labels={"revenue": "Revenue ($)", "region": "Region"})

    @render_widget
    def revenue_trend():
        df = filtered().groupby(["date", "product"], as_index=False)["revenue"].sum()
        return px.line(df, x="date", y="revenue", color="product",
                       title="Weekly Revenue Trend by Product",
                       labels={"revenue": "Revenue ($)", "date": "Week", "product": "Product"})


app = App(app_ui, server)
